# Application properties for Quarkus OIDC configuration
quarkus.oidc.client-id=quarkus-backend
quarkus.oidc.auth-server-url=http://localhost:8081/realms/task-manager
quarkus.oidc.frontend.credentials.secret=${KEYCLOAK_CLIENT_SECRET}
quarkus.oidc.application-type=service
# Disable TLS verification for development purposes (not recommended for production)
quarkus.tls.trust-all=true
quarkus.tls.hostname-verification-algorithm=NONE
# Configure security for the application endpoints
## Require authentication for API endpoints
quarkus.http.auth.permission.authenticated.paths=/api/*
quarkus.http.auth.permission.authenticated.policy=authenticated
## Allow unauthenticated access to the frontend, as it will handle authentication via OIDC
quarkus.http.auth.permission.frontend.paths=/app/*
quarkus.http.auth.permission.frontend.policy=permit
## Allow unauthenticated access to the Quarkus Dev UI and Swagger UI
quarkus.http.auth.permission.quarkusdev.paths=/q/*
quarkus.http.auth.permission.quarkusdev.policy=permit
# Swagger UI configuration
%prod.quarkus.swagger-ui.always-include=false
%dev.quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/q/swagger
quarkus.smallrye-openapi.security-scheme=oidc
quarkus.smallrye-openapi.security-scheme-name=Keycloak
quarkus.smallrye-openapi.oidc-open-id-connect-url=http://localhost:8081/realms/task-manager/.well-known/openid-configuration
# Database configuration
quarkus.datasource.db-kind=postgresql
## Use environment variables for database credentials and connection details
%dev.quarkus.datasource.username=${POSTGRES_USER}
%prod.quarkus.datasource.username=${POSTGRES_USER}
%dev.quarkus.datasource.password=${POSTGRES_PASSWORD}
%prod.quarkus.datasource.password=${POSTGRES_PASSWORD}
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB}
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB}
# Hibernate configuration
# quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.log.sql=true
# Keycloak Admin Client configuration
keycloak.admin.client.url=http://localhost:8081
keycloak.admin.client.realm=task-manager
keycloak.admin.client.username=admin
keycloak.admin.client.password=admin
keycloak.admin.client.client-id=admin-cli
quarkus.keycloak.admin-client.server-url=${keycloak.admin.client.url}
# Test profile configuration
%test.quarkus.oidc.tenant-enabled=false
%test.quarkus.oidc.frontend.tenant-enabled=false
%test.quarkus.keycloak.policy-enforcer.enable=false
%test.quarkus.keycloak.devservices.enabled=false
%test.quarkus.quinoa.enabled=false
%test.quarkus.hibernate-orm.log.sql=false
%test.quarkus.hibernate-orm.schema-management.strategy=drop-and-create
