# Application properties for Quarkus OIDC configuration

quarkus.oidc.back.client-id=quarkus-backend
quarkus.oidc.back.auth-server-url=http://localhost:8443/realms/task-manager
quarkus.oidc.frontend.credentials.secret=${KEYCLOAK_CLIENT_SECRET}
quarkus.oidc.back.application-type=service


# quarkus.oidc.client-id=quarkus-react
# quarkus.oidc.application-type=web-app
# # %prod.quarkus.oidc.auth-server-url=http://localhost:8443/realms/quarkus
# quarkus.oidc.auth-server-url=http://localhost:8443/realms/task-manager
quarkus.http.auth.permission.authenticated.paths=/api/*
quarkus.http.auth.permission.authenticated.policy=authenticated

quarkus.http.auth.permission.frontend.paths=/app/*
# Allow unauthenticated access to the frontend, as it will handle authentication via OIDC
quarkus.http.auth.permission.frontend.policy=permit

quarkus.http.auth.permission.quarkusdev.paths=/q/*
quarkus.http.auth.permission.quarkusdev.policy=permit
