# Application properties for Quarkus OIDC configuration

quarkus.oidc.client-id=quarkus-backend
quarkus.oidc.auth-server-url=http://localhost:8081/realms/task-manager
quarkus.oidc.frontend.credentials.secret=${KEYCLOAK_CLIENT_SECRET}
quarkus.oidc.application-type=service

quarkus.oidc.tls.verification=none

quarkus.http.auth.permission.authenticated.paths=/api/*
quarkus.http.auth.permission.authenticated.policy=authenticated

quarkus.http.auth.permission.frontend.paths=/app/*
# Allow unauthenticated access to the frontend, as it will handle authentication via OIDC
quarkus.http.auth.permission.frontend.policy=permit

quarkus.http.auth.permission.quarkusdev.paths=/q/*
quarkus.http.auth.permission.quarkusdev.policy=permit

%prod.quarkus.swagger-ui.always-include=false
%dev.quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/q/swagger
quarkus.smallrye-openapi.security-scheme=oidc
quarkus.smallrye-openapi.security-scheme-name=Keycloak
quarkus.smallrye-openapi.oidc-open-id-connect-url=http://localhost:8081/realms/task-manager/.well-known/openid-configuration
